// File generated by FlutterFire CLI / TaxiGo setup.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for TaxiGo (project: taxigo-e7b4b).
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO3xY5spGJvVnTLP1B-GswxWbv2NFCb3M',
    appId: '1:728811081033:android:f5f0f0e02b3d6b51bade98',
    messagingSenderId: '728811081033',
    projectId: 'taxigo-e7b4b',
    databaseURL: 'https://taxigo-e7b4b-default-rtdb.firebaseio.com',
    storageBucket: 'taxigo-e7b4b.firebasestorage.app',
  );

  /// Bundle ID must match Xcode: com.erhancinar.taxigo
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr32dVV_5dXDI09l559XaDIIdwzK5YRsI',
    appId: '1:728811081033:ios:a9bbd3a01c41ee05bade98',
    messagingSenderId: '728811081033',
    projectId: 'taxigo-e7b4b',
    databaseURL: 'https://taxigo-e7b4b-default-rtdb.firebaseio.com',
    storageBucket: 'taxigo-e7b4b.firebasestorage.app',
    iosBundleId: 'com.erhancinar.taxigo',
  );
}
