/// Dial codes for phone collection after social login.
class CountryDialCode {
  const CountryDialCode({
    required this.name,
    required this.iso2,
    required this.dialCode,
    required this.flag,
  });

  final String name;
  final String iso2;
  final String dialCode;
  final String flag;

  String get label => '$flag  $name ($dialCode)';
}

/// Default: Montenegro (service region).
const kDefaultCountryDial = CountryDialCode(
  name: 'Montenegro',
  iso2: 'ME',
  dialCode: '+382',
  flag: '🇲🇪',
);

const kCountryDialCodes = <CountryDialCode>[
  CountryDialCode(name: 'Afghanistan', iso2: 'AF', dialCode: '+93', flag: '🇦🇫'),
  CountryDialCode(name: 'Albania', iso2: 'AL', dialCode: '+355', flag: '🇦🇱'),
  CountryDialCode(name: 'Algeria', iso2: 'DZ', dialCode: '+213', flag: '🇩🇿'),
  CountryDialCode(name: 'Andorra', iso2: 'AD', dialCode: '+376', flag: '🇦🇩'),
  CountryDialCode(name: 'Angola', iso2: 'AO', dialCode: '+244', flag: '🇦🇴'),
  CountryDialCode(name: 'Argentina', iso2: 'AR', dialCode: '+54', flag: '🇦🇷'),
  CountryDialCode(name: 'Armenia', iso2: 'AM', dialCode: '+374', flag: '🇦🇲'),
  CountryDialCode(name: 'Australia', iso2: 'AU', dialCode: '+61', flag: '🇦🇺'),
  CountryDialCode(name: 'Austria', iso2: 'AT', dialCode: '+43', flag: '🇦🇹'),
  CountryDialCode(name: 'Azerbaijan', iso2: 'AZ', dialCode: '+994', flag: '🇦🇿'),
  CountryDialCode(name: 'Bahrain', iso2: 'BH', dialCode: '+973', flag: '🇧🇭'),
  CountryDialCode(name: 'Bangladesh', iso2: 'BD', dialCode: '+880', flag: '🇧🇩'),
  CountryDialCode(name: 'Belarus', iso2: 'BY', dialCode: '+375', flag: '🇧🇾'),
  CountryDialCode(name: 'Belgium', iso2: 'BE', dialCode: '+32', flag: '🇧🇪'),
  CountryDialCode(name: 'Bosnia and Herzegovina', iso2: 'BA', dialCode: '+387', flag: '🇧🇦'),
  CountryDialCode(name: 'Brazil', iso2: 'BR', dialCode: '+55', flag: '🇧🇷'),
  CountryDialCode(name: 'Bulgaria', iso2: 'BG', dialCode: '+359', flag: '🇧🇬'),
  CountryDialCode(name: 'Canada', iso2: 'CA', dialCode: '+1', flag: '🇨🇦'),
  CountryDialCode(name: 'Chile', iso2: 'CL', dialCode: '+56', flag: '🇨🇱'),
  CountryDialCode(name: 'China', iso2: 'CN', dialCode: '+86', flag: '🇨🇳'),
  CountryDialCode(name: 'Colombia', iso2: 'CO', dialCode: '+57', flag: '🇨🇴'),
  CountryDialCode(name: 'Croatia', iso2: 'HR', dialCode: '+385', flag: '🇭🇷'),
  CountryDialCode(name: 'Cyprus', iso2: 'CY', dialCode: '+357', flag: '🇨🇾'),
  CountryDialCode(name: 'Czech Republic', iso2: 'CZ', dialCode: '+420', flag: '🇨🇿'),
  CountryDialCode(name: 'Denmark', iso2: 'DK', dialCode: '+45', flag: '🇩🇰'),
  CountryDialCode(name: 'Egypt', iso2: 'EG', dialCode: '+20', flag: '🇪🇬'),
  CountryDialCode(name: 'Estonia', iso2: 'EE', dialCode: '+372', flag: '🇪🇪'),
  CountryDialCode(name: 'Finland', iso2: 'FI', dialCode: '+358', flag: '🇫🇮'),
  CountryDialCode(name: 'France', iso2: 'FR', dialCode: '+33', flag: '🇫🇷'),
  CountryDialCode(name: 'Georgia', iso2: 'GE', dialCode: '+995', flag: '🇬🇪'),
  CountryDialCode(name: 'Germany', iso2: 'DE', dialCode: '+49', flag: '🇩🇪'),
  CountryDialCode(name: 'Greece', iso2: 'GR', dialCode: '+30', flag: '🇬🇷'),
  CountryDialCode(name: 'Hong Kong', iso2: 'HK', dialCode: '+852', flag: '🇭🇰'),
  CountryDialCode(name: 'Hungary', iso2: 'HU', dialCode: '+36', flag: '🇭🇺'),
  CountryDialCode(name: 'Iceland', iso2: 'IS', dialCode: '+354', flag: '🇮🇸'),
  CountryDialCode(name: 'India', iso2: 'IN', dialCode: '+91', flag: '🇮🇳'),
  CountryDialCode(name: 'Indonesia', iso2: 'ID', dialCode: '+62', flag: '🇮🇩'),
  CountryDialCode(name: 'Iran', iso2: 'IR', dialCode: '+98', flag: '🇮🇷'),
  CountryDialCode(name: 'Iraq', iso2: 'IQ', dialCode: '+964', flag: '🇮🇶'),
  CountryDialCode(name: 'Ireland', iso2: 'IE', dialCode: '+353', flag: '🇮🇪'),
  CountryDialCode(name: 'Israel', iso2: 'IL', dialCode: '+972', flag: '🇮🇱'),
  CountryDialCode(name: 'Italy', iso2: 'IT', dialCode: '+39', flag: '🇮🇹'),
  CountryDialCode(name: 'Japan', iso2: 'JP', dialCode: '+81', flag: '🇯🇵'),
  CountryDialCode(name: 'Jordan', iso2: 'JO', dialCode: '+962', flag: '🇯🇴'),
  CountryDialCode(name: 'Kazakhstan', iso2: 'KZ', dialCode: '+7', flag: '🇰🇿'),
  CountryDialCode(name: 'Kosovo', iso2: 'XK', dialCode: '+383', flag: '🇽🇰'),
  CountryDialCode(name: 'Kuwait', iso2: 'KW', dialCode: '+965', flag: '🇰🇼'),
  CountryDialCode(name: 'Latvia', iso2: 'LV', dialCode: '+371', flag: '🇱🇻'),
  CountryDialCode(name: 'Lebanon', iso2: 'LB', dialCode: '+961', flag: '🇱🇧'),
  CountryDialCode(name: 'Lithuania', iso2: 'LT', dialCode: '+370', flag: '🇱🇹'),
  CountryDialCode(name: 'Luxembourg', iso2: 'LU', dialCode: '+352', flag: '🇱🇺'),
  CountryDialCode(name: 'Malaysia', iso2: 'MY', dialCode: '+60', flag: '🇲🇾'),
  CountryDialCode(name: 'Malta', iso2: 'MT', dialCode: '+356', flag: '🇲🇹'),
  CountryDialCode(name: 'Mexico', iso2: 'MX', dialCode: '+52', flag: '🇲🇽'),
  kDefaultCountryDial,
  CountryDialCode(name: 'Morocco', iso2: 'MA', dialCode: '+212', flag: '🇲🇦'),
  CountryDialCode(name: 'Netherlands', iso2: 'NL', dialCode: '+31', flag: '🇳🇱'),
  CountryDialCode(name: 'New Zealand', iso2: 'NZ', dialCode: '+64', flag: '🇳🇿'),
  CountryDialCode(name: 'Nigeria', iso2: 'NG', dialCode: '+234', flag: '🇳🇬'),
  CountryDialCode(name: 'North Macedonia', iso2: 'MK', dialCode: '+389', flag: '🇲🇰'),
  CountryDialCode(name: 'Norway', iso2: 'NO', dialCode: '+47', flag: '🇳🇴'),
  CountryDialCode(name: 'Oman', iso2: 'OM', dialCode: '+968', flag: '🇴🇲'),
  CountryDialCode(name: 'Pakistan', iso2: 'PK', dialCode: '+92', flag: '🇵🇰'),
  CountryDialCode(name: 'Palestine', iso2: 'PS', dialCode: '+970', flag: '🇵🇸'),
  CountryDialCode(name: 'Poland', iso2: 'PL', dialCode: '+48', flag: '🇵🇱'),
  CountryDialCode(name: 'Portugal', iso2: 'PT', dialCode: '+351', flag: '🇵🇹'),
  CountryDialCode(name: 'Qatar', iso2: 'QA', dialCode: '+974', flag: '🇶🇦'),
  CountryDialCode(name: 'Romania', iso2: 'RO', dialCode: '+40', flag: '🇷🇴'),
  CountryDialCode(name: 'Russia', iso2: 'RU', dialCode: '+7', flag: '🇷🇺'),
  CountryDialCode(name: 'Saudi Arabia', iso2: 'SA', dialCode: '+966', flag: '🇸🇦'),
  CountryDialCode(name: 'Serbia', iso2: 'RS', dialCode: '+381', flag: '🇷🇸'),
  CountryDialCode(name: 'Singapore', iso2: 'SG', dialCode: '+65', flag: '🇸🇬'),
  CountryDialCode(name: 'Slovakia', iso2: 'SK', dialCode: '+421', flag: '🇸🇰'),
  CountryDialCode(name: 'Slovenia', iso2: 'SI', dialCode: '+386', flag: '🇸🇮'),
  CountryDialCode(name: 'South Africa', iso2: 'ZA', dialCode: '+27', flag: '🇿🇦'),
  CountryDialCode(name: 'South Korea', iso2: 'KR', dialCode: '+82', flag: '🇰🇷'),
  CountryDialCode(name: 'Spain', iso2: 'ES', dialCode: '+34', flag: '🇪🇸'),
  CountryDialCode(name: 'Sweden', iso2: 'SE', dialCode: '+46', flag: '🇸🇪'),
  CountryDialCode(name: 'Switzerland', iso2: 'CH', dialCode: '+41', flag: '🇨🇭'),
  CountryDialCode(name: 'Syria', iso2: 'SY', dialCode: '+963', flag: '🇸🇾'),
  CountryDialCode(name: 'Taiwan', iso2: 'TW', dialCode: '+886', flag: '🇹🇼'),
  CountryDialCode(name: 'Thailand', iso2: 'TH', dialCode: '+66', flag: '🇹🇭'),
  CountryDialCode(name: 'Tunisia', iso2: 'TN', dialCode: '+216', flag: '🇹🇳'),
  CountryDialCode(name: 'Turkey', iso2: 'TR', dialCode: '+90', flag: '🇹🇷'),
  CountryDialCode(name: 'Ukraine', iso2: 'UA', dialCode: '+380', flag: '🇺🇦'),
  CountryDialCode(name: 'United Arab Emirates', iso2: 'AE', dialCode: '+971', flag: '🇦🇪'),
  CountryDialCode(name: 'United Kingdom', iso2: 'GB', dialCode: '+44', flag: '🇬🇧'),
  CountryDialCode(name: 'United States', iso2: 'US', dialCode: '+1', flag: '🇺🇸'),
  CountryDialCode(name: 'Uzbekistan', iso2: 'UZ', dialCode: '+998', flag: '🇺🇿'),
  CountryDialCode(name: 'Vietnam', iso2: 'VN', dialCode: '+84', flag: '🇻🇳'),
];
